baseURL = "https://jreisinger.github.io/" # Hostname (and path) to the root.
title = "/home/jreisinger" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Jozef Reisinger" # Author's name.
    info = "Sr. Human Being" # Author's job title or info.
    description = "Jozef Reisinger's home page" # Site description.
    keywords = "Linux,programming,security,sysadmin,devops,personal" # Site keywords.
    #avatarurl = "images/avatar.jpeg" # Contain the path of the optionnal avatar in the static folder.
    #avatarurl = "img/go.png"
    #footercontent = "Enter a text here." # Add footer content

    #disqusShortname = "" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

# Social links
[[params.social]]
    name = "Blog"
    url  = "https://jreisinger.github.com/blog2/"
[[params.social]]
    name = "Notes"
    url  = "https://reisinge.net/notes/"
[[params.social]]
    name = "Code"
    url = "https://github.com/jreisinger/"
[[params.social]]
    name = "Q&A"
    url = "https://stackoverflow.com/users/1039320/jreisinger"

# Menu links
[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "CV"
    url = "/cv/"
# [[menu.main]]
#     name = "Links"
#     weight = 3
#     url  = "/links/"
# [[menu.main]]
#     name = "Posts"
#     weight = 4
#     url  = "/posts/"
