baseURL = "http://jreisinger.github.io/" # Hostname (and path) to the root.
title = "reisinge" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Jozef Reisinger" # Author's name.
    info = "Human being, husband, father, DevOps" # Author's job title or info.
    description = "Jozef Reisinger's personal website" # Site description.
    keywords = "Linux,programming,security,sysadmin,devops,personal" # Site keywords.

    disqusShortname = "yourdiscussshortname" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
	  custom_css = []

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/jreisinger/"
[[params.social]]
    name = "StackExchange"
    weight = 2
    url = "https://stackexchange.com/users/1010742/jreisinger"
[[params.social]]
    name = "The Monastery"
    weight = 3
    url = "http://perlmonks.org/?node_id=6364;user=reisinge"
[[params.social]]
    name = "Twitter"
    weight = 4
    url = "https://twitter.com/JozefReisinger/"
[[params.social]]
    name = "LinkedIn"
    weight = 5
    url = "https://sk.linkedin.com/in/jozefreisinger"
[[params.social]]
    name = "Blog"
    weight = 6
    url  = "https://jreisinger.blogspot.com/"
[[params.social]]
    name = "Wiki"
    weight = 7
    url  = "http://wiki.reisinge.net/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "CV"
    weight = 2
    url = "/cv/"
[[menu.main]]
    name = "Links"
    weight = 3
    url  = "/links/"
