baseURL = "http://jreisinger.github.io/" # Hostname (and path) to the root.
title = "$USER" # Site title.
theme = "hugo-coder" # Set the theme.
languagecode = "en" # The site’s language code.

paginate = 20 # Default number of pages per page in pagination.
canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.

[params] # theme parameters
    author = "Jozef Reisinger" # Author's name.
    info = "Human being" # Author's job title or info.
    description = "Jozef Reisinger's home page" # Site description.
    keywords = "Linux,programming,security,sysadmin,devops,personal" # Site keywords.
    #avatarurl = "images/avatar.jpeg" # Contain the path of the optionnal avatar in the static folder.
    #footercontent = "Enter a text here." # Add footer content

    disqusShortname = "jreisinger" # Enable or disable Disqus

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = true

    # Custom CSS
	  custom_css = []

# Social links
[[params.social]]
    name = "Code"
    weight = 1
    url = "https://github.com/jreisinger/"
[[params.social]]
    name = "Blog"
    weight = 2
    url  = "https://github.com/jreisinger/blog"
[[params.social]]
    name = "Wiki"
    weight = 3
    url  = "http://wiki.reisinge.net/"
[[params.social]]
    name = "Q&A"
    weight = 4
    url = "https://stackoverflow.com/users/1039320/jreisinger"
[[params.social]]
    name = "Monastery"
    weight = 5
    url = "http://perlmonks.org/?node_id=6364;user=reisinge"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "CV"
    weight = 2
    url = "/cv/"
# [[menu.main]]
#     name = "Links"
#     weight = 3
#     url  = "/links/"
[[menu.main]]
    name = "Posts"
    weight = 4
    url  = "/posts/"
